CREATE TABLE DEVMON (
    id_devmon NUMBER NOT NULL,
    nome VARCHAR2(200) NOT NULL,
    vidaMAX NUMBER(4) NOT NULL,
    vida NUMBER(4) NOT NULL,
    atk NUMBER(3) NOT NULL,
    def NUMBER(3) NOT NULL, 
    PRIMARY KEY (id_devmon),
    CONSTRAINT UK_ID_DEVMON UNIQUE (id_devmon)
    );

   CREATE SEQUENCE SEQ_DEVMON
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE
;